['/**\n',
 ' * Created by LimeChat\n',
 ' */\n',
 " var fs = require('fs');\n",
 " var error = 'error';\n",
 ' \n',
 ' module.exports = {\n',
 '     home: home,\n',
 '     demos : demos,\n',
 '     superbottoms : superbottoms,\n',
 '     kaya : kaya,\n',
 '     sugar : sugar,\n',
 '     azah : azah,\n',
 '     sirona : sirona,\n',
 '     flintobox : flintobox,\n',
 '     manmatters : manmatters,\n',
 '     caratlane : caratlane,\n',
 '     bewakoof : bewakoof,\n',
 '     bodywise : bodywise,\n',
 '     anveshan : anveshan,\n',
 '     kapiva : kapiva,\n',
 '     herbobuild : herbobuild,\n',
 '     churchillshoes : churchillshoes,\n',
 '     bellavita : bellavita,\n',
 '     aadar : aadar,\n',
 '     themancompany : themancompany,\n',
 '     giva : giva,\n',
 '     traya : traya,\n',
 '     nissan: nissan,\n',
 '     theartment: theartment,\n',
 '     boldcare: boldcare,\n',
 '     andme: andme,\n',
 '     wowskinscience: wowskinscience,\n',
 '     damensch: damensch,\n',
 '     vahdamteas: vahdamteas,\n',
 '     adilqadri: adilqadri,\n',
 '     plixlife : plixlife,\n',
 '     mamaearth: mamaearth,\n',
 '     sarva : sarva,\n',
 '     gynoveda: gynoveda,\n',
 '     theayurvedaco: theayurvedaco,\n',
 '     supertails: supertails,\n',
 '     snazzyalign: snazzyalign,\n',
 '     shopg: shopg,\n',
 '     urbangabru: urbangabru,\n',
 '     ravinjeans: ravinjeans,\n',
 '     onmen: onmen,\n',
 '     tae: tae,\n',
 '     pilgrim: pilgrim,\n',
 '     coolberg: coolberg,\n',
 '     ragecoffee: ragecoffee,\n',
 '     arata: arata,\n',
 '     thejuneshop: thejuneshop,\n',
 '     sanfe: sanfe,\n',
 '     xyxx: xyxx,\n',
 '     autobot: autobot,\n',
 '     //Prod exports\n',
 '     anveshan_prod : anveshan_prod,\n',
 '     aadar_prod : aadar_prod,\n',
 '     manmatters_prod : manmatters_prod,\n',
 '     kapiva_prod : kapiva_prod,\n',
 '     captainzack_prod : captainzack_prod,\n',
 '     coccoon_prod : coccoon_prod,\n',
 '     bellavita_prod : bellavita_prod,\n',
 '     azah_prod : azah_prod,\n',
 '     drvaidya_prod : drvaidya_prod,\n',
 '     churchillshoes_prod : churchillshoes_prod,\n',
 '     bodywise_prod : bodywise_prod,\n',
 '     herbobuild_prod : herbobuild_prod,\n',
 '     themancompany_prod : themancompany_prod,\n',
 '     giva_prod : giva_prod,\n',
 '     error_404: error_404,\n',
 '     error_500: error_500,\n',
 '     nirogam : nirogam,\n',
 '     nirogam_prod : nirogam_prod,\n',
 '     traya_prod : traya_prod,\n',
 '     nissan_prod : nissan_prod,\n',
 '     theartment_prod : theartment_prod,\n',
 '     boldcare_prod : boldcare_prod,\n',
 '     andme_prod: andme_prod,\n',
 '     wowskinscience_prod: wowskinscience_prod,\n',
 '     damensch_prod: damensch_prod,\n',
 '     vahdamteas_prod: vahdamteas_prod,\n',
 '     mamaearth_prod: mamaearth_prod,\n',
 '     adilqadri_prod: adilqadri_prod,\n',
 '     plixlife_prod : plixlife_prod,\n',
 '     sarva_prod : sarva_prod,\n',
 '     gynoveda_prod: gynoveda_prod,\n',
 '     theayurvedaco_prod: theayurvedaco_prod,\n',
 '     supertails_prod: supertails_prod,\n',
 '     snazzyalign_prod: snazzyalign_prod,\n',
 '     shopg_prod: shopg_prod,\n',
 '     urbangabru_prod: urbangabru_prod,\n',
 '     ravinjeans_prod: ravinjeans_prod,\n',
 '     onmen_prod: onmen_prod,\n',
 '     tae_prod: tae_prod,\n',
 '     pilgrim_prod: pilgrim_prod,\n',
 '     coolberg_prod: coolberg_prod,\n',
 '     ragecoffee_prod: ragecoffee_prod,\n',
 '     arata_prod: arata_prod,\n',
 '     thejuneshop_prod: thejuneshop_prod,\n',
 '     sanfe_prod: sanfe_prod,\n',
 '     xyxx_prod: xyxx_prod\n',
 '     autobot_prod: autobot_prod\n',
 ' };\n',
 ' \n',
 ' //==========================================================\n',
 ' //==================== GET REQUEST =========================\n',
 ' //==========================================================\n',
 ' \n',
 ' // Error Pages\n',
 ' function error_404(req : any, res : any) {\n',
 "     res.render(error + '/404.ejs', {\n",
 "         title: '404 Error'\n",
 '     });\n',
 ' }\n',
 ' \n',
 ' function error_500(req : any, res : any) {\n',
 "     res.render(error + '/500.ejs', {\n",
 "         title: '500 Error'\n",
 '     });\n',
 ' }\n',
 ' \n',
 ' \n',
 ' // LimeChat Pages\n',
 ' function home(req : any, res : any) {\n',
 "     res.render('index.html', {\n",
 '         user: req.session.user,\n',
 "         title: 'LimeChat Demo'\n",
 '     });\n',
 ' }\n',
 ' \n',
 ' function demos(req : any, res : any) {\n',
 "     res.render('demos.html', {\n",
 '         user: req.session.user,\n',
 "         title: 'LimeChat Demo'\n",
 '     });\n',
 ' }\n',
 ' \n',
 ' // Testing Exports\n',
 ' function superbottoms(req : any, res : any) {\n',
 "     res.render('company/superbottoms.html', {\n",
 '         user: req.session.user,\n',
 "         title: 'LimeChat Demo'\n",
 '     });\n',
 ' }\n',
 ' \n',
 ' function kaya(req : any, res : any) {\n',
 "     res.render('company/kaya.html', {\n",
 '         user: req.session.user,\n',
 "         title: 'LimeChat Demo'\n",
 '     });\n',
 ' }\n',
 ' \n',
 ' function sugar(req : any, res : any) {\n',
 "     res.render('company/sugar.html', {\n",
 '         user: req.session.user,\n',
 "         title: 'LimeChat Demo'\n",
 '     });\n',
 ' }\n',
 ' \n',
 ' function azah(req : any, res : any) {\n',
 "     res.render('company/azah.html', {\n",
 '         user: req.session.user,\n',
 "         title: 'LimeChat Demo'\n",
 '     });\n',
 ' }\n',
 ' \n',
 ' function sirona(req : any, res : any) {\n',
 "     res.render('company/sirona.html', {\n",
 '         user: req.session.user,\n',
 "         title: 'LimeChat Demo'\n",
 '     });\n',
 ' }\n',
 ' \n',
 ' function flintobox(req : any, res : any) {\n',
 "     res.render('company/flintobox.html', {\n",
 '         user: req.session.user,\n',
 "         title: 'LimeChat Demo'\n",
 '     });\n',
 ' }\n',
 ' \n',
 ' function manmatters(req : any, res : any) {\n',
 "     res.render('company/manmatters.html', {\n",
 '         user: req.session.user,\n',
 "         title: 'LimeChat Demo'\n",
 '     });\n',
 ' }\n',
 ' \n',
 ' function caratlane(req : any, res : any) {\n',
 "     res.render('company/caratlane.html', {\n",
 '         user: req.session.user,\n',
 "         title: 'LimeChat Demo'\n",
 '     });\n',
 ' }\n',
 ' \n',
 ' function bewakoof(req : any, res : any) {\n',
 "     res.render('company/bewakoof.html', {\n",
 '         user: req.session.user,\n',
 "         title: 'LimeChat Demo'\n",
 '     });\n',
 ' }\n',
 ' \n',
 ' function bodywise(req : any, res : any) {\n',
 "     res.render('company/bodywise.html', {\n",
 '         user: req.session.user,\n',
 "         title: 'LimeChat Demo'\n",
 '     });\n',
 ' }\n',
 ' \n',
 ' function anveshan(req : any, res : any) {\n',
 "     res.render('company/anveshan.html', {\n",
 '         user: req.session.user,\n',
 "         title: 'LimeChat Demo'\n",
 '     });\n',
 ' }\n',
 ' \n',
 ' function kapiva(req : any, res : any) {\n',
 "     res.render('company/kapiva.html', {\n",
 '         user: req.session.user,\n',
 "         title: 'LimeChat Demo'\n",
 '     });\n',
 ' }\n',
 ' \n',
 ' function churchillshoes(req : any, res : any) {\n',
 "     res.render('company/churchillshoes.html', {\n",
 '         user: req.session.user,\n',
 "         title: 'LimeChat Demo'\n",
 '     });\n',
 ' }\n',
 ' \n',
 ' function herbobuild(req : any, res : any) {\n',
 "     res.render('company/herbobuild.html', {\n",
 '         user: req.session.user,\n',
 "         title: 'LimeChat Demo'\n",
 '     });\n',
 ' }\n',
 ' \n',
 ' function bellavita(req : any, res : any) {\n',
 "     res.render('company/bellavita.html', {\n",
 '         user: req.session.user,\n',
 "         title: 'LimeChat Demo'\n",
 '     });\n',
 ' }\n',
 ' \n',
 ' function coolberg(req : any, res : any) {\n',
 "     res.render('company/coolberg.html', {\n",
 '         user: req.session.user,\n',
 "         title: 'LimeChat Demo'\n",
 '     });\n',
 ' }\n',
 ' \n',
 ' function thejuneshop(req : any, res : any) {\n',
 "     res.render('company/thejuneshop.html', {\n",
 '         user: req.session.user,\n',
 "         title: 'LimeChat Demo'\n",
 '     });\n',
 ' }\n',
 ' \n',
 ' function aadar(req : any, res : any) {\n',
 "     res.render('company/aadar.html', {\n",
 '         user: req.session.user,\n',
 "         title: 'LimeChat Demo'\n",
 '     });\n',
 ' }\n',
 ' \n',
 ' function themancompany(req : any, res : any) {\n',
 "     res.render('company/themancompany.html', {\n",
 '         user: req.session.user,\n',
 "         title: 'LimeChat Demo'\n",
 '     });\n',
 ' }\n',
 ' \n',
 ' function giva(req : any, res : any) {\n',
 "     res.render('company/giva.html', {\n",
 '         user: req.session.user,\n',
 "         title: 'LimeChat Demo'\n",
 '     });\n',
 ' }\n',
 ' \n',
 ' function nirogam(req : any, res : any) {\n',
 "     res.render('company/nirogam.html', {\n",
 '         user: req.session.user,\n',
 "         title: 'LimeChat Demo'\n",
 '     });\n',
 ' }\n',
 ' \n',
 ' function traya(req : any, res : any) {\n',
 "     res.render('company/traya.html', {\n",
 '         user: req.session.user,\n',
 "         title: 'LimeChat Demo'\n",
 '     });\n',
 ' }\n',
 ' \n',
 ' function nissan(req : any, res : any) {\n',
 "     res.render('company/nissan.html', {\n",
 '         user: req.session.user,\n',
 "         title: 'LimeChat Demo'\n",
 '     });\n',
 ' }\n',
 ' \n',
 ' function theartment(req : any, res : any) {\n',
 "     res.render('company/theartment.html', {\n",
 '         user: req.session.user,\n',
 "         title: 'LimeChat Demo'\n",
 '     });\n',
 ' }\n',
 ' \n',
 ' function boldcare(req : any, res : any) {\n',
 "     res.render('company/boldcare.html', {\n",
 '         user: req.session.user,\n',
 "         title: 'LimeChat Demo'\n",
 '     });\n',
 ' }\n',
 ' \n',
 ' function andme(req : any, res : any) {\n',
 "     res.render('company/andme.html', {\n",
 '         user: req.session.user,\n',
 "         title: 'LimeChat Demo'\n",
 '     });\n',
 ' }\n',
 ' \n',
 ' function wowskinscience(req : any, res : any) {\n',
 "     res.render('company/wowskinscience.html', {\n",
 '         user: req.session.user,\n',
 "         title: 'LimeChat Demo'\n",
 '     });\n',
 ' }\n',
 ' \n',
 ' function damensch(req : any, res : any) {\n',
 "     res.render('company/damensch.html', {\n",
 '         user: req.session.user,\n',
 "         title: 'LimeChat Demo for Damensch'\n",
 '     });\n',
 ' }\n',
 ' \n',
 ' function vahdamteas(req : any, res : any) {\n',
 "     res.render('company/vahdamteas.html', {\n",
 '         user: req.session.user,\n',
 "         title: 'LimeChat Demo'\n",
 '     });\n',
 ' }\n',
 ' \n',
 ' function mamaearth(req : any, res : any) {\n',
 "     res.render('company/mamaearth.html', {\n",
 '         user: req.session.user,\n',
 "         title: 'LimeChat Demo'\n",
 '     });\n',
 ' }\n',
 ' function adilqadri(req : any, res : any) {\n',
 "     res.render('company/adilqadri.html', {\n",
 '         user: req.session.user,\n',
 "         title: 'LimeChat Demo'\n",
 '     });\n',
 ' }\n',
 ' function gynoveda(req : any, res : any) {\n',
 "     res.render('company/gynoveda.html', {\n",
 '         user: req.session.user,\n',
 "         title: 'LimeChat Demo'\n",
 '     });\n',
 ' }\n',
 ' \n',
 ' \n',
 ' function plixlife(req : any, res : any) {\n',
 "     res.render('company/plixlife.html', {\n",
 '         user: req.session.user,\n',
 "         title: 'LimeChat Demo'\n",
 '     });\n',
 ' }\n',
 ' \n',
 ' function sarva(req : any, res : any) {\n',
 "     res.render('company/sarva.html', {\n",
 '         user: req.session.user,\n',
 "         title: 'LimeChat Demo'\n",
 '     });\n',
 ' }\n',
 ' \n',
 ' function theayurvedaco(req : any, res : any) {\n',
 "     res.render('company/theayurvedaco.html', {\n",
 '         user: req.session.user,\n',
 "         title: 'LimeChat Demo'\n",
 '     });\n',
 ' }\n',
 ' \n',
 ' function supertails(req : any, res : any) {\n',
 "     res.render('company/supertails.html', {\n",
 '         user: req.session.user,\n',
 "         title: 'LimeChat Demo'\n",
 '     });\n',
 ' }\n',
 ' \n',
 ' function snazzyalign(req : any, res : any) {\n',
 "     res.render('company/snazzyalign.html', {\n",
 '         user: req.session.user,\n',
 "         title: 'LimeChat Demo'\n",
 '     });\n',
 ' }\n',
 ' \n',
 ' function shopg(req : any, res : any) {\n',
 "     res.render('company/shopg.html', {\n",
 '         user: req.session.user,\n',
 "         title: 'LimeChat Demo'\n",
 '     });\n',
 ' }\n',
 ' \n',
 ' function urbangabru(req : any, res : any) {\n',
 "     res.render('company/urbangabru.html', {\n",
 '         user: req.session.user,\n',
 "         title: 'LimeChat Demo'\n",
 '     });\n',
 ' }\n',
 ' \n',
 ' function ravinjeans(req : any, res : any) {\n',
 "     res.render('company/ravinjeans.html', {\n",
 '         user: req.session.user,\n',
 "         title: 'LimeChat Demo'\n",
 '     });\n',
 ' }\n',
 ' \n',
 ' function onmen(req : any, res : any) {\n',
 "     res.render('company/onmen.html', {\n",
 '         user: req.session.user,\n',
 "         title: 'LimeChat Demo'\n",
 '     });\n',
 ' }\n',
 ' \n',
 ' function tae(req : any, res : any) {\n',
 "     res.render('company/tae.html', {\n",
 '         user: req.session.user,\n',
 "         title: 'LimeChat Demo'\n",
 '     });\n',
 ' }\n',
 ' \n',
 ' function pilgrim(req : any, res : any) {\n',
 "     res.render('company/pilgrim.html', {\n",
 '         user: req.session.user,\n',
 "         title: 'LimeChat Demo'\n",
 '     });\n',
 ' }\n',
 ' \n',
 ' function ragecoffee(req : any, res : any) {\n',
 "     res.render('company/ragecoffee.html', {\n",
 '         user: req.session.user,\n',
 "         title: 'LimeChat Demo'\n",
 '     });\n',
 ' }\n',
 ' \n',
 ' function arata(req : any, res : any) {\n',
 "     res.render('company/arata.html', {\n",
 '         user: req.session.user,\n',
 "         title: 'LimeChat Demo'\n",
 '     });\n',
 ' }\n',
 ' \n',
 ' function sanfe(req : any, res : any) {\n',
 "     res.render('company/sanfe.html', {\n",
 '         user: req.session.user,\n',
 "         title: 'LimeChat Demo'\n",
 '     });\n',
 ' }\n',
 ' \n',
 ' function xyxx(req : any, res : any) {\n',
 "     res.render('company/xyxx.html', {\n",
 '         user: req.session.user,\n',
 "         title: 'LimeChat Demo'\n",
 '     });\n',
 ' }\n',
 ' // Production Exports\n',
 ' function aadar_prod(req : any, res : any) {\n',
 "     res.render('production/aadar.html', {\n",
 '         user: req.session.user,\n',
 "         title: 'LimeChat Demo'\n",
 '     });\n',
 ' }\n',
 ' \n',
 ' function azah_prod(req : any, res : any) {\n',
 "     res.render('production/azah.html', {\n",
 '         user: req.session.user,\n',
 "         title: 'LimeChat Demo'\n",
 '     });\n',
 ' }\n',
 ' \n',
 ' function bellavita_prod(req : any, res : any) {\n',
 "     res.render('production/bellavita.html', {\n",
 '         user: req.session.user,\n',
 "         title: 'LimeChat Demo'\n",
 '     });\n',
 ' }\n',
 ' \n',
 ' function captainzack_prod(req : any, res : any) {\n',
 "     res.render('production/captainzack.html', {\n",
 '         user: req.session.user,\n',
 "         title: 'LimeChat Demo'\n",
 '     });\n',
 ' }\n',
 ' \n',
 ' function coccoon_prod(req : any, res : any) {\n',
 "     res.render('production/coccoon.html', {\n",
 '         user: req.session.user,\n',
 "         title: 'LimeChat Demo'\n",
 '     });\n',
 ' }\n',
 ' \n',
 ' function manmatters_prod(req : any, res : any) {\n',
 "     res.render('production/manmatters.html', {\n",
 '         user: req.session.user,\n',
 "         title: 'LimeChat Demo'\n",
 '     });\n',
 ' }\n',
 ' \n',
 ' function churchillshoes_prod(req : any, res : any) {\n',
 "     res.render('production/churchillshoes.html', {\n",
 '         user: req.session.user,\n',
 "         title: 'LimeChat Demo'\n",
 '     });\n',
 ' }\n',
 ' \n',
 ' function kapiva_prod(req : any, res : any) {\n',
 "     res.render('production/kapiva.html', {\n",
 '         user: req.session.user,\n',
 "         title: 'LimeChat Demo'\n",
 '     });\n',
 ' }\n',
 ' \n',
 ' function drvaidya_prod(req : any, res : any) {\n',
 "     res.render('production/drvaidya.html', {\n",
 '         user: req.session.user,\n',
 "         title: 'LimeChat Demo'\n",
 '     });\n',
 ' }\n',
 ' \n',
 ' function thejuneshop_prod(req : any, res : any) {\n',
 "     res.render('production/thejuneshop.html', {\n",
 '         user: req.session.user,\n',
 "         title: 'LimeChat Demo'\n",
 '     });\n',
 ' }\n',
 ' \n',
 ' function anveshan_prod(req : any, res : any) {\n',
 "     res.render('production/anveshan.html', {\n",
 '         user: req.session.user,\n',
 "         title: 'LimeChat Demo'\n",
 '     });\n',
 ' }\n',
 ' \n',
 ' function bodywise_prod(req : any, res : any) {\n',
 "     res.render('production/bodywise.html', {\n",
 '         user: req.session.user,\n',
 "         title: 'LimeChat Demo'\n",
 '     });\n',
 ' }\n',
 ' \n',
 ' function herbobuild_prod(req : any, res : any) {\n',
 "     res.render('production/herbobuild.html', {\n",
 '         user: req.session.user,\n',
 "         title: 'LimeChat Demo'\n",
 '     });\n',
 ' }\n',
 ' \n',
 ' function themancompany_prod(req : any, res : any) {\n',
 "     res.render('production/themancompany.html', {\n",
 '         user: req.session.user,\n',
 "         title: 'LimeChat Demo'\n",
 '     });\n',
 ' }\n',
 ' \n',
 ' function giva_prod(req : any, res : any) {\n',
 "     res.render('production/giva.html', {\n",
 '         user: req.session.user,\n',
 "         title: 'LimeChat Demo'\n",
 '     });\n',
 ' }\n',
 ' \n',
 ' function nirogam_prod(req : any, res : any) {\n',
 "     res.render('production/nirogam.html', {\n",
 '         user: req.session.user,\n',
 "         title: 'LimeChat Demo'\n",
 '     });\n',
 ' }\n',
 ' \n',
 ' function traya_prod(req : any, res : any) {\n',
 "     res.render('production/traya.html', {\n",
 '         user: req.session.user,\n',
 "         title: 'LimeChat Demo'\n",
 '     });\n',
 ' }\n',
 ' \n',
 ' function nissan_prod(req : any, res : any) {\n',
 "     res.render('production/nissan.html', {\n",
 '         user: req.session.user,\n',
 "         title: 'LimeChat Demo'\n",
 '     });\n',
 ' }\n',
 ' \n',
 ' function theartment_prod(req : any, res : any) {\n',
 "     res.render('production/theartment.html', {\n",
 '         user: req.session.user,\n',
 "         title: 'LimeChat Demo'\n",
 '     });\n',
 ' }\n',
 ' \n',
 ' function boldcare_prod(req : any, res : any) {\n',
 "     res.render('production/boldcare.html', {\n",
 '         user: req.session.user,\n',
 "         title: 'LimeChat Demo'\n",
 '     });\n',
 ' }\n',
 ' \n',
 ' function andme_prod(req : any, res : any) {\n',
 "     res.render('production/andme.html', {\n",
 '         user: req.session.user,\n',
 "         title: 'LimeChat Demo'\n",
 '     });\n',
 ' }\n',
 ' \n',
 ' function wowskinscience_prod(req : any, res : any) {\n',
 "     res.render('production/wowskinscience.html', {\n",
 '         user: req.session.user,\n',
 "         title: 'LimeChat Demo'\n",
 '     });\n',
 ' }\n',
 ' \n',
 ' function damensch_prod(req : any, res : any) {\n',
 "     res.render('production/damensch.html', {\n",
 '         user: req.session.user,\n',
 "         title: 'LimeChat Demo for Damensch'\n",
 '     });\n',
 ' }\n',
 ' \n',
 ' function vahdamteas_prod(req : any, res : any) {\n',
 "     res.render('production/vahdamteas.html', {\n",
 '         user: req.session.user,\n',
 "         title: 'LimeChat Demo'\n",
 '     });\n',
 ' }\n',
 ' \n',
 ' function mamaearth_prod(req : any, res : any) {\n',
 "     res.render('production/mamaearth.html', {\n",
 '         user: req.session.user,\n',
 "         title: 'LimeChat Demo'\n",
 '     });\n',
 ' }\n',
 ' function gynoveda_prod(req : any, res : any) {\n',
 "     res.render('production/gynoveda.html', {\n",
 '         user: req.session.user,\n',
 "         title: 'LimeChat Demo'\n",
 '     });\n',
 ' }\n',
 ' function adilqadri_prod(req : any, res : any) {\n',
 "     res.render('production/adilqadri.html', {\n",
 '         user: req.session.user,\n',
 "         title: 'LimeChat Demo'\n",
 '     });\n',
 ' }\n',
 ' \n',
 ' function plixlife_prod(req : any, res : any) {\n',
 "     res.render('production/plixlife.html', {\n",
 '         user: req.session.user,\n',
 "         title: 'LimeChat Demo'\n",
 '     });\n',
 ' }\n',
 ' \n',
 ' function coolberg_prod(req : any, res : any) {\n',
 "     res.render('production/coolberg.html', {\n",
 '         user: req.session.user,\n',
 "         title: 'LimeChat Demo'\n",
 '     });\n',
 ' }\n',
 ' \n',
 ' function sarva_prod(req : any, res : any) {\n',
 "     res.render('production/sarva.html', {\n",
 '         user: req.session.user,\n',
 "         title: 'LimeChat Demo'\n",
 '     });\n',
 ' }\n',
 ' \n',
 ' function theayurvedaco_prod(req : any, res : any) {\n',
 "     res.render('production/theayurvedaco.html', {\n",
 '         user: req.session.user,\n',
 "         title: 'LimeChat Demo'\n",
 '     });\n',
 ' }\n',
 ' \n',
 ' function supertails_prod(req : any, res : any) {\n',
 "     res.render('production/supertails.html', {\n",
 '         user: req.session.user,\n',
 "         title: 'LimeChat Demo'\n",
 '     });\n',
 ' }\n',
 ' \n',
 ' function snazzyalign_prod(req : any, res : any) {\n',
 "     res.render('production/snazzyalign.html', {\n",
 '         user: req.session.user,\n',
 "         title: 'LimeChat Demo'\n",
 '     });\n',
 ' }\n',
 ' \n',
 ' function shopg_prod(req : any, res : any) {\n',
 "     res.render('production/shopg.html', {\n",
 '         user: req.session.user,\n',
 "         title: 'LimeChat Demo'\n",
 '     });\n',
 ' }\n',
 ' \n',
 ' function urbangabru_prod(req : any, res : any) {\n',
 "     res.render('production/urbangabru.html', {\n",
 '         user: req.session.user,\n',
 "         title: ':LimeChat Demo'\n",
 '     });\n',
 ' }\n',
 ' \n',
 ' function ravinjeans_prod(req : any, res : any) {\n',
 "     res.render('production/ravinjeans.html', {\n",
 '         user: req.session.user,\n',
 "         title: 'LimeChat Demo'\n",
 '     });\n',
 ' }\n',
 ' \n',
 ' function onmen_prod(req : any, res : any) {\n',
 "     res.render('production/onmen.html', {\n",
 '         user: req.session.user,\n',
 "         title: 'LimeChat Demo'\n",
 '     });\n',
 ' }\n',
 ' \n',
 ' function tae_prod(req : any, res : any) {\n',
 "     res.render('production/tae.html', {\n",
 '         user: req.session.user,\n',
 "         title: 'LimeChat Demo'\n",
 '     });\n',
 ' }\n',
 ' \n',
 ' function pilgrim_prod(req : any, res : any) {\n',
 "     res.render('production/pilgrim.html', {\n",
 '         user: req.session.user,\n',
 "         title: 'LimeChat Demo'\n",
 '     });\n',
 ' }\n',
 ' function ragecoffee_prod(req : any, res : any) {\n',
 "     res.render('production/ragecoffee.html', {\n",
 '         user: req.session.user,\n',
 "         title: 'LimeChat Demo'\n",
 '     });\n',
 ' }\n',
 ' \n',
 ' function arata_prod(req : any, res : any) {\n',
 "     res.render('production/arata.html', {\n",
 '         user: req.session.user,\n',
 "         title: 'LimeChat Demo'\n",
 '     });\n',
 ' }\n',
 ' \n',
 ' function sanfe_prod(req : any, res : any) {\n',
 "     res.render('production/sanfe.html', {\n",
 '         user: req.session.user,\n',
 "         title: 'LimeChat Demo'\n",
 '     });\n',
 ' }\n',
 ' \n',
 ' function xyxx_prod(req : any, res : any) {\n',
 "     res.render('production/xyxx.html', {\n",
 '         user: req.session.user,\n',
 "         title: 'LimeChat Demo'\n",
 '     });\n',
 ' }']